# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileBrowser.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 460)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setIconSize(QtCore.QSize(200, 180))
        self.listWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setGridSize(QtCore.QSize(220, 190))
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotType = QtWidgets.QComboBox(Form)
        self.plotType.setMaximumSize(QtCore.QSize(100, 16777215))
        self.plotType.setObjectName("plotType")
        self.plotType.addItem("")
        self.plotType.addItem("")
        self.horizontalLayout.addWidget(self.plotType)
        self.newPlotFrame = QtWidgets.QFrame(Form)
        self.newPlotFrame.setEnabled(True)
        self.newPlotFrame.setMinimumSize(QtCore.QSize(10, 0))
        self.newPlotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.newPlotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.newPlotFrame.setObjectName("newPlotFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.newPlotFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fitType = QtWidgets.QComboBox(self.newPlotFrame)
        self.fitType.setEnabled(True)
        self.fitType.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fitType.setObjectName("fitType")
        self.fitType.addItem("")
        self.fitType.addItem("")
        self.horizontalLayout_2.addWidget(self.fitType)
        self.errorBars = QtWidgets.QCheckBox(self.newPlotFrame)
        self.errorBars.setEnabled(True)
        self.errorBars.setObjectName("errorBars")
        self.horizontalLayout_2.addWidget(self.errorBars)
        self.plotLog = QtWidgets.QCheckBox(self.newPlotFrame)
        self.plotLog.setObjectName("plotLog")
        self.horizontalLayout_2.addWidget(self.plotLog)
        self.horizontalLayout.addWidget(self.newPlotFrame)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pattern = QtWidgets.QLineEdit(Form)
        self.pattern.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pattern.setObjectName("pattern")
        self.horizontalLayout.addWidget(self.pattern)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dirChange = QtWidgets.QPushButton(self.frame)
        self.dirChange.setMinimumSize(QtCore.QSize(0, 0))
        self.dirChange.setMaximumSize(QtCore.QSize(150, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/control/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dirChange.setIcon(icon)
        self.dirChange.setObjectName("dirChange")
        self.gridLayout_2.addWidget(self.dirChange, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)
        self.pathLabel = QtWidgets.QLabel(self.frame)
        self.pathLabel.setWordWrap(True)
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout_2.addWidget(self.pathLabel, 1, 0, 1, 5)
        self.fileOpenButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileOpenButton.sizePolicy().hasHeightForWidth())
        self.fileOpenButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/control/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpenButton.setIcon(icon1)
        self.fileOpenButton.setObjectName("fileOpenButton")
        self.gridLayout_2.addWidget(self.fileOpenButton, 0, 0, 1, 1)
        self.dirChange_2 = QtWidgets.QPushButton(self.frame)
        self.dirChange_2.setMinimumSize(QtCore.QSize(0, 0))
        self.dirChange_2.setMaximumSize(QtCore.QSize(150, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/control/projectfolder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dirChange_2.setIcon(icon2)
        self.dirChange_2.setObjectName("dirChange_2")
        self.gridLayout_2.addWidget(self.dirChange_2, 0, 3, 1, 1)
        self.fileOpenButton_2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileOpenButton_2.sizePolicy().hasHeightForWidth())
        self.fileOpenButton_2.setSizePolicy(sizePolicy)
        self.fileOpenButton_2.setIcon(icon1)
        self.fileOpenButton_2.setObjectName("fileOpenButton_2")
        self.gridLayout_2.addWidget(self.fileOpenButton_2, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.comments = QtWidgets.QTextBrowser(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments.sizePolicy().hasHeightForWidth())
        self.comments.setSizePolicy(sizePolicy)
        self.comments.setMinimumSize(QtCore.QSize(0, 0))
        self.comments.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comments.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.comments.setOpenLinks(False)
        self.comments.setObjectName("comments")
        self.gridLayout.addWidget(self.comments, 2, 1, 1, 1)

        self.retranslateUi(Form)
        self.dirChange.clicked.connect(Form.changeDirectory)
        self.plotType.currentIndexChanged['int'].connect(Form.plotTypeChanged)
        self.listWidget.itemClicked['QListWidgetItem*'].connect(Form.itemClicked)
        self.listWidget.itemDoubleClicked['QListWidgetItem*'].connect(Form.itemDoubleClicked)
        self.pattern.returnPressed.connect(Form.patternChanged)
        self.fileOpenButton.clicked.connect(Form.browseFile)
        self.dirChange_2.clicked.connect(Form.loadProject)
        self.fileOpenButton_2.clicked.connect(Form.browseListFile)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plotType.setItemText(0, _translate("Form", "Histogram"))
        self.plotType.setItemText(1, _translate("Form", "Half Life"))
        self.fitType.setItemText(0, _translate("Form", "No Fit"))
        self.fitType.setItemText(1, _translate("Form", "Exponential Decay"))
        self.errorBars.setText(_translate("Form", "Error Bars"))
        self.plotLog.setText(_translate("Form", "Log"))
        self.label.setText(_translate("Form", "Filter files:"))
        self.pattern.setText(_translate("Form", "*"))
        self.frame.setProperty("class", _translate("Form", "deep"))
        self.dirChange.setText(_translate("Form", "Select Directory"))
        self.pathLabel.setText(_translate("Form", "Directory:"))
        self.fileOpenButton.setText(_translate("Form", "Open HISTOGRAM"))
        self.dirChange_2.setText(_translate("Form", "Load Project"))
        self.fileOpenButton_2.setText(_translate("Form", "Open LIST DATA"))
        self.comments.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>"))

from . import res_rc
