# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/control/plots.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTip("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(25, 25))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.mainTab = QtWidgets.QWidget()
        self.mainTab.setObjectName("mainTab")
        self.plot_area = QtWidgets.QVBoxLayout(self.mainTab)
        self.plot_area.setContentsMargins(0, 0, 0, 0)
        self.plot_area.setObjectName("plot_area")
        self.tabWidget.addTab(self.mainTab, icon, "")
        self.saveTab = QtWidgets.QWidget()
        self.saveTab.setObjectName("saveTab")
        self.saveLayout = QtWidgets.QVBoxLayout(self.saveTab)
        self.saveLayout.setContentsMargins(0, 0, 0, 0)
        self.saveLayout.setObjectName("saveLayout")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/control/saved.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.saveTab, icon1, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.controlDock = QtWidgets.QDockWidget(MainWindow)
        self.controlDock.setFloating(False)
        self.controlDock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.controlDock.setObjectName("controlDock")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgets = QtWidgets.QFrame(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgets.sizePolicy().hasHeightForWidth())
        self.widgets.setSizePolicy(sizePolicy)
        self.widgets.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgets.setAutoFillBackground(False)
        self.widgets.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.widgets.setFrameShadow(QtWidgets.QFrame.Raised)
        self.widgets.setObjectName("widgets")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgets)
        self.verticalLayout.setObjectName("verticalLayout")
        self.acquisitionFrame = AnimatedFrame(self.widgets)
        self.acquisitionFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.acquisitionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.acquisitionFrame.setObjectName("acquisitionFrame")
        self.acquisitionLayout = QtWidgets.QGridLayout(self.acquisitionFrame)
        self.acquisitionLayout.setContentsMargins(0, 0, 0, 0)
        self.acquisitionLayout.setObjectName("acquisitionLayout")
        self.startButton = QtWidgets.QPushButton(self.acquisitionFrame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/control/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon2)
        self.startButton.setObjectName("startButton")
        self.acquisitionLayout.addWidget(self.startButton, 0, 0, 1, 1)
        self.autoUpdateBox = QtWidgets.QCheckBox(self.acquisitionFrame)
        self.autoUpdateBox.setObjectName("autoUpdateBox")
        self.acquisitionLayout.addWidget(self.autoUpdateBox, 4, 1, 1, 1)
        self.updateButton = QtWidgets.QPushButton(self.acquisitionFrame)
        self.updateButton.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/control/reset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateButton.setIcon(icon3)
        self.updateButton.setObjectName("updateButton")
        self.acquisitionLayout.addWidget(self.updateButton, 4, 0, 1, 1)
        self.autoUpdateSettings = QtWidgets.QToolButton(self.acquisitionFrame)
        self.autoUpdateSettings.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/control/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.autoUpdateSettings.setIcon(icon4)
        self.autoUpdateSettings.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.autoUpdateSettings.setArrowType(QtCore.Qt.NoArrow)
        self.autoUpdateSettings.setObjectName("autoUpdateSettings")
        self.acquisitionLayout.addWidget(self.autoUpdateSettings, 4, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.acquisitionFrame)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.acquisitionLayout.addWidget(self.line_8, 3, 0, 1, 3)
        self.progressBar = QtWidgets.QProgressBar(self.acquisitionFrame)
        self.progressBar.setEnabled(False)
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.acquisitionLayout.addWidget(self.progressBar, 5, 0, 1, 3)
        self.clearButton = QtWidgets.QPushButton(self.acquisitionFrame)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/control/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon5)
        self.clearButton.setObjectName("clearButton")
        self.acquisitionLayout.addWidget(self.clearButton, 1, 0, 1, 3)
        self.pauseButton = QtWidgets.QPushButton(self.acquisitionFrame)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/control/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon6)
        self.pauseButton.setObjectName("pauseButton")
        self.acquisitionLayout.addWidget(self.pauseButton, 0, 1, 1, 2)
        self.verticalLayout.addWidget(self.acquisitionFrame)
        self.countLabel = QtWidgets.QPushButton(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.countLabel.setFont(font)
        self.countLabel.setText("")
        self.countLabel.setFlat(True)
        self.countLabel.setObjectName("countLabel")
        self.verticalLayout.addWidget(self.countLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.widgets)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 2)
        self.summationButton = QtWidgets.QPushButton(self.widgets)
        self.summationButton.setObjectName("summationButton")
        self.gridLayout.addWidget(self.summationButton, 7, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fitButton = QtWidgets.QPushButton(self.widgets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitButton.sizePolicy().hasHeightForWidth())
        self.fitButton.setSizePolicy(sizePolicy)
        self.fitButton.setObjectName("fitButton")
        self.horizontalLayout_4.addWidget(self.fitButton)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.widgets)
        self.checkBox.setEnabled(False)
        self.checkBox.setChecked(True)
        self.checkBox.setAutoRepeat(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.lowTailBox = QtWidgets.QCheckBox(self.widgets)
        self.lowTailBox.setObjectName("lowTailBox")
        self.verticalLayout_2.addWidget(self.lowTailBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 2)
        self.logBox = QtWidgets.QCheckBox(self.widgets)
        self.logBox.setStyleSheet("")
        self.logBox.setIcon(icon)
        self.logBox.setObjectName("logBox")
        self.gridLayout.addWidget(self.logBox, 1, 1, 1, 1)
        self.binLabel = QtWidgets.QLabel(self.widgets)
        self.binLabel.setObjectName("binLabel")
        self.gridLayout.addWidget(self.binLabel, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.regionLabel = QtWidgets.QPushButton(self.widgets)
        self.regionLabel.setObjectName("regionLabel")
        self.horizontalLayout_3.addWidget(self.regionLabel)
        self.addButton_2 = QtWidgets.QPushButton(self.widgets)
        self.addButton_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.addButton_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/control/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton_2.setIcon(icon7)
        self.addButton_2.setObjectName("addButton_2")
        self.horizontalLayout_3.addWidget(self.addButton_2)
        self.addButton_3 = QtWidgets.QPushButton(self.widgets)
        self.addButton_3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.addButton_3.setText("")
        self.addButton_3.setIcon(icon5)
        self.addButton_3.setObjectName("addButton_3")
        self.horizontalLayout_3.addWidget(self.addButton_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.line_9 = QtWidgets.QFrame(self.widgets)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 3, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_6 = QtWidgets.QFrame(self.widgets)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calibrationButton = QtWidgets.QPushButton(self.widgets)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.calibrationButton.setFont(font)
        self.calibrationButton.setIcon(icon4)
        self.calibrationButton.setFlat(True)
        self.calibrationButton.setObjectName("calibrationButton")
        self.gridLayout_2.addWidget(self.calibrationButton, 1, 1, 1, 1)
        self.calibrateOnOff = QtWidgets.QCheckBox(self.widgets)
        self.calibrateOnOff.setMaximumSize(QtCore.QSize(25, 16777215))
        self.calibrateOnOff.setText("")
        self.calibrateOnOff.setObjectName("calibrateOnOff")
        self.gridLayout_2.addWidget(self.calibrateOnOff, 1, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.widgets)
        self.addButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.addButton.setText("")
        self.addButton.setIcon(icon7)
        self.addButton.setObjectName("addButton")
        self.gridLayout_2.addWidget(self.addButton, 1, 2, 1, 1)
        self.calLabel = QtWidgets.QLabel(self.widgets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calLabel.sizePolicy().hasHeightForWidth())
        self.calLabel.setSizePolicy(sizePolicy)
        self.calLabel.setMinimumSize(QtCore.QSize(60, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calLabel.setFont(font)
        self.calLabel.setStyleSheet("")
        self.calLabel.setObjectName("calLabel")
        self.gridLayout_2.addWidget(self.calLabel, 2, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_7 = QtWidgets.QFrame(self.widgets)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.widgets)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("saveall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon8)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.line_4 = QtWidgets.QFrame(self.widgets)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.currentFrame = QtWidgets.QFrame(self.widgets)
        self.currentFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.currentFrame.setObjectName("currentFrame")
        self.currentLayout = QtWidgets.QVBoxLayout(self.currentFrame)
        self.currentLayout.setContentsMargins(0, 0, 0, 0)
        self.currentLayout.setSpacing(1)
        self.currentLayout.setObjectName("currentLayout")
        self.label_3 = QtWidgets.QLabel(self.currentFrame)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.currentLayout.addWidget(self.label_3)
        self.currentLabel = QtWidgets.QLabel(self.currentFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentLabel.sizePolicy().hasHeightForWidth())
        self.currentLabel.setSizePolicy(sizePolicy)
        self.currentLabel.setMinimumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currentLabel.setFont(font)
        self.currentLabel.setObjectName("currentLabel")
        self.currentLayout.addWidget(self.currentLabel)
        self.verticalLayout.addWidget(self.currentFrame)
        self.temperatureLabel = QtWidgets.QLabel(self.widgets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureLabel.sizePolicy().hasHeightForWidth())
        self.temperatureLabel.setSizePolicy(sizePolicy)
        self.temperatureLabel.setMinimumSize(QtCore.QSize(60, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.temperatureLabel.setFont(font)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.verticalLayout.addWidget(self.temperatureLabel)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(7, 2)
        self.verticalLayout.setStretch(8, 2)
        self.verticalLayout_3.addWidget(self.widgets)
        self.controlDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.controlDock)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.updateButton.clicked.connect(MainWindow.load)
        self.summationButton.clicked.connect(MainWindow.summation)
        self.addButton_2.clicked.connect(MainWindow.insertRegion)
        self.calibrateOnOff.toggled['bool'].connect(MainWindow.toggleCalibration)
        self.regionLabel.clicked.connect(MainWindow.showRegionWindow)
        self.calibrationButton.clicked.connect(MainWindow.showCalibrationEditor)
        self.clearButton.clicked.connect(MainWindow.clear)
        self.logBox.clicked['bool'].connect(MainWindow.toggleLog)
        self.startButton.clicked.connect(MainWindow.start)
        self.fitButton.clicked.connect(MainWindow.fit)
        self.pauseButton.clicked.connect(MainWindow.pause)
        self.pushButton_6.clicked.connect(MainWindow.save)
        self.countLabel.clicked.connect(MainWindow.clearCount)
        self.addButton.clicked.connect(MainWindow.addSelectedPoint)
        self.addButton_3.clicked.connect(MainWindow.removeRegion)
        self.autoUpdateBox.clicked['bool'].connect(MainWindow.autoUpdateEnable)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CSpark Research : Multi Channel Analyzer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mainTab), _translate("MainWindow", "Histogram"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.mainTab), _translate("MainWindow", "Data Acquisition and controls"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saveTab), _translate("MainWindow", "Saved plots"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.saveTab), _translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">View saved plots. Click on them to load them to the plot window for analysis.</span></p><p><span style=\" font-size:14pt;\">Automatically generates a thumbnail view for the chosen directory</span></p></body></html>"))
        self.controlDock.setWindowTitle(_translate("MainWindow", "Instrument Controls"))
        self.startButton.setToolTip(_translate("MainWindow", "Start acquiring and sorting pulses"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.autoUpdateBox.setToolTip(_translate("MainWindow", "Auto update the graph"))
        self.autoUpdateBox.setText(_translate("MainWindow", "Auto"))
        self.updateButton.setToolTip(_translate("MainWindow", "Load histogram onto the graph"))
        self.updateButton.setText(_translate("MainWindow", "UPDATE"))
        self.clearButton.setToolTip(_translate("MainWindow", "Clear the histogram"))
        self.clearButton.setText(_translate("MainWindow", "CLEAR"))
        self.pauseButton.setToolTip(_translate("MainWindow", "Pause data acquisition"))
        self.pauseButton.setText(_translate("MainWindow", "STOP   "))
        self.countLabel.setToolTip(_translate("MainWindow", "Total Input Pulses. Click to clear the counter"))
        self.summationButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">After selecting a region by inserting a</span><span style=\" font-size:14pt; text-decoration: underline;\"> Graph Region </span><span style=\" font-size:14pt;\">and dragging it to select the appropriate channels,</span></p><p><span style=\" font-size:14pt;\">click to get the total number of events recorded in that region.</span></p><p><span style=\" font-size:14pt;\"><br/></span></p><p><span style=\" font-size:14pt;\">This is useful for half life and branching ratio calculations.</span></p></body></html>"))
        self.summationButton.setText(_translate("MainWindow", "Summation of Region"))
        self.fitButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/control/plot.svg\"/></p><p><span style=\" font-size:12pt; text-decoration: underline;\">After selecting a region </span><span style=\" font-size:12pt;\">by inserting a graph region,</span></p><p><span style=\" font-size:12pt;\">click to here to extract parameters using a gaussian fit .</span></p><p>If any attenuation is present, select the \'Low-Energy Tail\' checkbox which combines a lorentzian function to get a better fit. FWHM is accordingly modified.<br/></p><p><span style=\" font-size:12pt;\">This will automatically switch to the calibration tab which will allow you to utilise the fitted values for analysis.</span></p></body></html>"))
        self.fitButton.setText(_translate("MainWindow", "FIT"))
        self.checkBox.setText(_translate("MainWindow", "Gaussian"))
        self.lowTailBox.setText(_translate("MainWindow", "Low-Energy Tail"))
        self.logBox.setText(_translate("MainWindow", "Log"))
        self.binLabel.setText(_translate("MainWindow", "Bins:"))
        self.regionLabel.setText(_translate("MainWindow", "Analyze Graph"))
        self.calibrationButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Switch to the calibration tab to modify the points considered.</span></p></body></html>"))
        self.calibrationButton.setText(_translate("MainWindow", "Calibration"))
        self.calibrateOnOff.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Enable/Disable the calibration polynomial.</span></p><p><span style=\" font-size:14pt;\">Switch to the calibration tab for details</span></p></body></html>"))
        self.addButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Manually add a calibration point.</p><p>Click on any known peak in the plot, and press this button to view a prompt that will ask you for the known energy in keV before adding it to the calibration point list.</p><p>The calibration polynomial is automatically updated</p></body></html>"))
        self.calLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p>Calibration polynomial which decides X axis scaling if calibration is enabled.</p><p>This is generated via the <span style=\" text-decoration: underline;\">Calibration</span> tab . Up to 2nd degree polynomial is possible.</p></body></html>"))
        self.calLabel.setText(_translate("MainWindow", "X\'  = X"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "Save acquired data as well as fitted data if any."))
        self.pushButton_6.setText(_translate("MainWindow", "Save Data"))
        self.label_3.setText(_translate("MainWindow", "Constant Current Source"))
        self.currentLabel.setToolTip(_translate("MainWindow", "Constant Current Source output voltage.\n"
"Colour changes to green for valid loads"))
        self.currentLabel.setText(_translate("MainWindow", "Source Preparation:"))
        self.temperatureLabel.setToolTip(_translate("MainWindow", "Constant Current Source output voltage.\n"
"Colour changes to green for valid loads"))
        self.temperatureLabel.setText(_translate("MainWindow", "temperature:"))

from utilities.animTools import AnimatedFrame
from . import res_rc
