# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotSave.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 534)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.headerText = QtWidgets.QLineEdit(self.centralwidget)
        self.headerText.setObjectName("headerText")
        self.gridLayout_2.addWidget(self.headerText, 0, 0, 1, 2)
        self.contents = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contents.sizePolicy().hasHeightForWidth())
        self.contents.setSizePolicy(sizePolicy)
        self.contents.setMaximumSize(QtCore.QSize(200, 16777215))
        self.contents.setObjectName("contents")
        self.gridLayout_2.addWidget(self.contents, 1, 0, 3, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 2, 1)
        self.headerBox = QtWidgets.QCheckBox(self.frame)
        self.headerBox.setChecked(False)
        self.headerBox.setObjectName("headerBox")
        self.gridLayout.addWidget(self.headerBox, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 2, 1)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 0, 2, 2, 2)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 7, 2, 1)
        self.delims = QtWidgets.QComboBox(self.frame)
        self.delims.setMaximumSize(QtCore.QSize(200, 16777215))
        self.delims.setObjectName("delims")
        self.delims.addItem("")
        self.delims.addItem("")
        self.delims.addItem("")
        self.delims.addItem("")
        self.gridLayout.addWidget(self.delims, 0, 6, 2, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 5, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 4, 2, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 8, 2, 1)
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 2, 0, 1, 9)
        self.plotSaveFrame = QtWidgets.QFrame(self.frame)
        self.plotSaveFrame.setEnabled(True)
        self.plotSaveFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.plotSaveFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plotSaveFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotSaveFrame.setObjectName("plotSaveFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.plotSaveFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.plotSaveFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.imageWidthBox = QtWidgets.QSpinBox(self.plotSaveFrame)
        self.imageWidthBox.setEnabled(False)
        self.imageWidthBox.setMinimum(100)
        self.imageWidthBox.setMaximum(4000)
        self.imageWidthBox.setObjectName("imageWidthBox")
        self.horizontalLayout.addWidget(self.imageWidthBox)
        self.line_7 = QtWidgets.QFrame(self.plotSaveFrame)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout.addWidget(self.line_7)
        self.saveImageButton = QtWidgets.QPushButton(self.plotSaveFrame)
        self.saveImageButton.setEnabled(False)
        self.saveImageButton.setObjectName("saveImageButton")
        self.horizontalLayout.addWidget(self.saveImageButton)
        self.gridLayout.addWidget(self.plotSaveFrame, 3, 5, 1, 4)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 4, 0, 1, 2)
        self.comments = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments.sizePolicy().hasHeightForWidth())
        self.comments.setSizePolicy(sizePolicy)
        self.comments.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comments.setReadOnly(False)
        self.comments.setObjectName("comments")
        self.gridLayout_2.addWidget(self.comments, 2, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.delims.setCurrentIndex(2)
        self.pushButton.clicked.connect(MainWindow.close)
        self.pushButton_2.clicked.connect(MainWindow.save)
        self.saveImageButton.clicked.connect(MainWindow.saveImage)
        self.pushButton_3.clicked.connect(MainWindow.projectSummary)
        self.delims.currentIndexChanged['int'].connect(MainWindow.delimiterChanged)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Save Your Results"))
        self.label_2.setText(_translate("MainWindow", "Comments"))
        self.headerBox.setText(_translate("MainWindow", "Include Headers"))
        self.pushButton.setText(_translate("MainWindow", "Cancel"))
        self.delims.setItemText(0, _translate("MainWindow", "space"))
        self.delims.setItemText(1, _translate("MainWindow", "tab"))
        self.delims.setItemText(2, _translate("MainWindow", "comma"))
        self.delims.setItemText(3, _translate("MainWindow", "semicolon"))
        self.label.setText(_translate("MainWindow", "Separator:"))
        self.pushButton_2.setText(_translate("MainWindow", "Save Data"))
        self.label_3.setText(_translate("MainWindow", "Width:"))
        self.saveImageButton.setText(_translate("MainWindow", "Save image"))
        self.pushButton_3.setText(_translate("MainWindow", "Generate Project Summary"))
        self.comments.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

