# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regionPopup.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(363, 459)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName("splitter")
        self.frame_3 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(280, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.frame)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.horizontalLayout.addWidget(self.commandLinkButton)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widgetLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.widgetLayout.setContentsMargins(0, 0, 0, 0)
        self.widgetLayout.setSpacing(3)
        self.widgetLayout.setObjectName("widgetLayout")
        self.verticalLayout.addWidget(self.frame_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.dirChange = QtWidgets.QPushButton(self.frame_3)
        self.dirChange.setMinimumSize(QtCore.QSize(0, 0))
        self.dirChange.setMaximumSize(QtCore.QSize(150, 30))
        self.dirChange.setObjectName("dirChange")
        self.gridLayout.addWidget(self.dirChange, 3, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.saveAllCheckbox = QtWidgets.QCheckBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAllCheckbox.sizePolicy().hasHeightForWidth())
        self.saveAllCheckbox.setSizePolicy(sizePolicy)
        self.saveAllCheckbox.setObjectName("saveAllCheckbox")
        self.gridLayout.addWidget(self.saveAllCheckbox, 2, 0, 1, 1)
        self.decayInterval = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.decayInterval.setMinimum(0.01)
        self.decayInterval.setMaximum(1000.0)
        self.decayInterval.setProperty("value", 30.0)
        self.decayInterval.setObjectName("decayInterval")
        self.gridLayout.addWidget(self.decayInterval, 1, 1, 1, 2)
        self.saveAllInterval = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAllInterval.sizePolicy().hasHeightForWidth())
        self.saveAllInterval.setSizePolicy(sizePolicy)
        self.saveAllInterval.setMinimum(1)
        self.saveAllInterval.setMaximum(60)
        self.saveAllInterval.setObjectName("saveAllInterval")
        self.gridLayout.addWidget(self.saveAllInterval, 2, 1, 1, 1)
        self.savedSpectraCounter = QtWidgets.QSpinBox(self.frame_3)
        self.savedSpectraCounter.setMaximumSize(QtCore.QSize(40, 16777215))
        self.savedSpectraCounter.setFrame(True)
        self.savedSpectraCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.savedSpectraCounter.setReadOnly(True)
        self.savedSpectraCounter.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.savedSpectraCounter.setKeyboardTracking(False)
        self.savedSpectraCounter.setMaximum(99999)
        self.savedSpectraCounter.setObjectName("savedSpectraCounter")
        self.gridLayout.addWidget(self.savedSpectraCounter, 2, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 150))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.graphFrame = QtWidgets.QFrame(self.splitter)
        self.graphFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphFrame.setObjectName("graphFrame")
        self.plotLayout = QtWidgets.QHBoxLayout(self.graphFrame)
        self.plotLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setSpacing(0)
        self.plotLayout.setObjectName("plotLayout")
        self.thumbs = QtWidgets.QListWidget(self.graphFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thumbs.sizePolicy().hasHeightForWidth())
        self.thumbs.setSizePolicy(sizePolicy)
        self.thumbs.setAcceptDrops(True)
        self.thumbs.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.thumbs.setProperty("showDropIndicator", False)
        self.thumbs.setDragEnabled(False)
        self.thumbs.setDragDropOverwriteMode(False)
        self.thumbs.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.thumbs.setAlternatingRowColors(True)
        self.thumbs.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.thumbs.setIconSize(QtCore.QSize(150, 150))
        self.thumbs.setFlow(QtWidgets.QListView.TopToBottom)
        self.thumbs.setResizeMode(QtWidgets.QListView.Fixed)
        self.thumbs.setViewMode(QtWidgets.QListView.ListMode)
        self.thumbs.setObjectName("thumbs")
        self.plotLayout.addWidget(self.thumbs)
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDump_To_Log = QtWidgets.QAction(MainWindow)
        self.actionDump_To_Log.setObjectName("actionDump_To_Log")

        self.retranslateUi(MainWindow)
        self.saveAllCheckbox.clicked.connect(MainWindow.enablePeriodicSpectrumSaving)
        self.checkBox_2.clicked['bool'].connect(MainWindow.showGraph)
        self.dirChange.clicked.connect(MainWindow.changeDirectory)
        self.decayInterval.editingFinished.connect(MainWindow.halflifeTime)
        self.commandLinkButton.clicked.connect(MainWindow.insertRegion)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Selection Regions"))
        self.commandLinkButton.setText(_translate("MainWindow", "Insert New Graph Selector"))
        self.checkBox_2.setText(_translate("MainWindow", "Graph"))
        self.dirChange.setText(_translate("MainWindow", "Select Directory"))
        self.label_5.setText(_translate("MainWindow", "Sum Record Interval"))
        self.saveAllCheckbox.setText(_translate("MainWindow", "Save Interval"))
        self.decayInterval.setSuffix(_translate("MainWindow", " Sec"))
        self.saveAllInterval.setSuffix(_translate("MainWindow", " Min"))
        self.actionDump_To_Log.setText(_translate("MainWindow", "Dump To Log"))

